PREBUILT_PATH := device/xiaomi/garnet-prebuilt

AB_OTA_PARTITIONS += \
    vendor_boot \
    vendor_dlkm

# Kernel (prebuilt)
BOARD_PREBUILT_DTBOIMAGE := $(PREBUILT_PATH)/images/dtbo.img

# Kernel modules (prebuilt)
DLKM_MODULES_PATH := $(PREBUILT_PATH)/modules/dlkm
RAMDISK_MODULES_PATH := $(PREBUILT_PATH)/modules/ramdisk

BOARD_VENDOR_KERNEL_MODULES := $(wildcard $(DLKM_MODULES_PATH)/*.ko)
BOARD_VENDOR_KERNEL_MODULES_LOAD := $(patsubst %,$(DLKM_MODULES_PATH)/%,$(shell cat $(DLKM_MODULES_PATH)/modules.load))
BOARD_VENDOR_KERNEL_MODULES_BLOCKLIST_FILE := $(DLKM_MODULES_PATH)/modules.blocklist

BOARD_VENDOR_RAMDISK_KERNEL_MODULES := $(wildcard $(RAMDISK_MODULES_PATH)/*.ko)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := $(patsubst %,$(RAMDISK_MODULES_PATH)/%,$(shell cat $(RAMDISK_MODULES_PATH)/modules.load))
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD  := $(patsubst %,$(RAMDISK_MODULES_PATH)/%,$(shell cat $(RAMDISK_MODULES_PATH)/modules.load.recovery))
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_BLOCKLIST_FILE := $(RAMDISK_MODULES_PATH)/modules.blocklist

# Partitions (prebuilt)
BOARD_PREBUILT_VENDOR_DLKMIMAGE := $(PREBUILT_PATH)/images/vendor_dlkm.img

BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += vendor_dlkm
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm
